### ISSUE TITLE
Client requests to https://dex.vidoardes.me/static/manifest.json yield 404 error

### ISSUE THREAD

**Issue by WindedHero** [vidoardes/dex#20]
The following body is received:
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> 
> <html><head>
> <title>404 Not Found</title>
> </head><body>
> <h1>Not Found</h1>
> <p>The requested URL /static/manifest.json was not found on this server.</p>
> </body></html>

Observed in Google Chrome console

**Comment by vidoardes** [comment]
Fixed
