### ISSUE TITLE
Negative filters / hide costumes

### ISSUE THREAD

**Issue by Stinolez** [vidoardes/dex#24]
Hi,
it'd be great if we had option to do negative filters to not to show the group. Mainly it's for the purpose of hiding the costume pokemons. I had several event pokemons, but cannot say for sure which one, so I decided not to track them (as they don't appear in game in pokedex).

Or it might be a good idea to put it as a DEX setting - to have option to either turn costumed pokemons off or on for the one DEX.

Thanks.
Cheers.

**Comment by vidoardes** [comment]
You can deselected costumed Pokemon from the settings, just uncheck Costumed under Show / Hide Forms
![image](https://user-images.githubusercontent.com/528854/65677425-7a43aa00-e049-11e9-8a83-2979f2286b33.png)
