### ISSUE TITLE
Clipboard string for [Not Owned] should be negated

### ISSUE THREAD

**Issue by WindedHero** [vidoardes/dex#25]
If you're looking at a [Not Owned] and [Lucky] list, or [Not Owned] and [Shiny] list, Dex displays pokemon you DON'T have. However, the clipboard search string searches for those pokemon AS [Shiny] or [Lucky]. 

Example:
Dex has [Owned] every lucky pokemon except a lucky caterpie. A normal caterpie is owned. 
Filtering Dex for [Not Owned] by itself lists nothing. Expected behavior.
Filtering Dex for [Not Owned] and [Lucky] lists only Caterpie. Expected behavior. 
The search string generated to the clipboard, however, searches for "10,&lucky" which would search your pokemon for Lucky Caterpie (which you have none of). Search would list nothing.
It should search instead for "10,&!lucky" to find not-lucky caterpie. 

Invert this issue for comparison:
Dex has [Owned] only a lucky caterpie. A normal caterpie is owned. 
Filtering Dex for [Owned] by itself lists everything. Expected behavior. 
Filtering Dex for [Owned] and [Lucky] yields only Lucky Caterpie. Expected behavior. 
The search string generated matches the displayed [Owned] and [Lucky] filter results. It searches for the same thing in the example above, "10,&lucky".

**Comment by vidoardes** [comment]
The idea behind the Not Owned filter is so that you can give it to someone else, so they can check if they have anything on your 'Not Owned' list to trade to you i.e "I don't have X, Y or Z, do you have these?"

I'm not sure what benefit invert it would have; would it not make more sense to select 'Owned' instead?

**Comment by WindedHero** [comment]
If the idea is to give it to someone else so they can check if they have anything on your "not owned" list, to what end? To trade? Can't trade a lucky.

**Comment by vidoardes** [comment]
That issue is specific to lucky though. In the case of a shiny, you wouldn't want to negate that. In the case of a shiny, regional, or any of the other categories that have keywords you would want it to stay in the positive. 

I can look at adding an exception for lucky

**Comment by WindedHero** [comment]
Excellent, thank you :)

**Comment by WindedHero** [comment]
I can't seem to make the clipboard function copy anything except an owned string, even when reloading the page and changing filters from [lucky] to [all] or [not owned] to [owned]

**Comment by vidoardes** [comment]
I've changed the way it generates, it is now paying attention to the owned / not owned filter, negates the lucky filter if not owned is selected, and is also now sorted numerically
