### ISSUE TITLE
Living Dex doesn't show pokemon from other lists

### ISSUE THREAD

**Issue by dingsbums** [vidoardes/dex#29]
Is that wanted behaviour and I am using it wrong? I added some pokemon to a lucky only list and none of those are in my "Living DEX" list. 

btw Firefox only shows first 25 pokemon. Chrome / Edge (Chromium) is fine.

**Comment by vidoardes** [comment]
The lists are designed to be independent, if you want to track them all in one list you can tick them as lucky in the living dex, and then use the filters to just see the lucky ones.

The Firefox issues was resolved last night.
