### ISSUE TITLE
Lucky Mythicals

### ISSUE THREAD

**Issue by RighteousPotato** [vidoardes/dex#3]
Minor bug: Mythical Pokemon cannot be traded and so it is not possible to obtain lucky versions of them - Dex currently allows users to mark Mew and Celebi as lucky

**Comment by vidoardes** [comment]
Good point, I hadn't considered that some Pokemon can't be lucky. I'll have to think a way around this one!

**Comment by vidoardes** [comment]
This has now been fixed

**Comment by RighteousPotato** [comment]
Commit a918495 does not in fact completely fix this issue. It stops Mythicals from showing in the lucky category, but does not stop the user from marking a Mythical as lucky
