### ISSUE TITLE
Please update new Shadow Pokemon

### ISSUE THREAD

**Issue by itchn4trbl** [vidoardes/dex#30]
Please update new shadow pokemon

**Comment by vidoardes** [comment]
I've added the following, let me know if I've missed any.

- Weedle
- Kakuna
- Beedrill
- Electabuzz
- Electavire
- Magmar
- Magmortar
- Lapras
- Mareep
- Seedot
- Nuzleaf
- Shiftry
- Sableye
- Trapinch
- Vibrava
- Flygon
- Cacnea
- Cacturne
- Shuppet
- Banette
- Duskull
- Dusclops
- Dusknoir
