### ISSUE TITLE
Purified not owned not sorting

### ISSUE THREAD

**Issue by itchn4trbl** [vidoardes/dex#34]
Thank you for updating the shadow list. The purified list is not sorting properly if you select Purified and not owned it selects all. Thank you for you work.

**Comment by vidoardes** [comment]
I am unable to replicate this issue, what is your username / list name?

**Comment by itchn4trbl** [comment]
GoddessEingana2 when I click purified it is not sorting I just getting all pokemon

**Comment by vidoardes** [comment]
This is now fixed
