### ISSUE TITLE
Pokemon missing

### ISSUE THREAD

**Issue by Nathan9696** [vidoardes/dex#35]
Hello,

Just wanted to let you know that a few Pokemon are missing :
- Galarian Weezing
- Burmy color variants + shiny
- Wormadam color variants + shiny
- Mothim shiny
- Cherrim color variants
- Shellos color variants
- Gastrodon color variants
- Giratina origin form
- Meltan + shiny
- Melmetal + shiny

Other mistakes:
- Regigigas should not have a male/female option, it should be genderless
- I can't add Cherrim to my list, nothing happens when I click on this Pokemon (whether it be the female, male or lucky button)
- Wormadam can't be male
- Mothim can't be female

Thanks in advance and thank you so much for the amazing work you do!

Best,

Nathan96

**Comment by Nathan9696** [comment]
Also:
- Wormadam can't be male
- Mothim can't be female

Thanks!

**Comment by vidoardes** [comment]
The variants are likely not ticked on your profile, if you go to Settings > Edit List you will see what is / isn't visible.

Shiny Burmy / Wormadam / Mothmin was missing, they are now added

Regigigas is now ungendered, and Wormadam and Mothmin now have the correct genders.

The issue with Cherrim when formes are hidden is also now fixed

I need to add some new filters for Galar formes so they will be added shortly

**Comment by vidoardes** [comment]
Galarian formes have now been added
