### ISSUE TITLE
Cryogonal Should Have No Gender

### ISSUE THREAD

**Issue by iamjohnford** [vidoardes/dex#38]
![image](https://user-images.githubusercontent.com/12647/71560429-e7475100-2a37-11ea-9591-33c68bc41f2e.png)
![IMG_7FA282A99BE3-1](https://user-images.githubusercontent.com/12647/71560443-0a720080-2a38-11ea-8f53-018b653f2239.jpeg)

**Comment by vidoardes** [comment]
That is now ungendered
