### ISSUE TITLE
Throh Appears to Only Have Male Form

### ISSUE THREAD

**Issue by iamjohnford** [vidoardes/dex#40]
![IMG_7E90F110A69C-1](https://user-images.githubusercontent.com/12647/72209959-a6f9c100-3482-11ea-873f-c997281cea9b.jpeg)

**Comment by iamjohnford** [comment]
Same goes for Sawk:

![IMG_9602](https://user-images.githubusercontent.com/12647/73365228-efceb980-4279-11ea-8acf-209c89453702.jpg)

**Comment by vidoardes** [comment]
Fixed
