### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by SonOfDiablo** [vidoardes/dex#44]
Hello, 

I just started using dex.vidoardes.me yesterday and while updating my dex I found the following issues:

Piplup (#393) and it's evolution chain is missing the shiny version in dex.

Sawk (#539) has a female version in dex but not in the Pokédex inside the game.

Scraggy (#559) is missing in dex.

I know the last time this repo was updated, was in December 2019, but I'm hoping the dev hasn't abandoned it completely.

**Comment by vidoardes** [comment]
The project is still active, updating which pokemon are released doesn't require code changes so you won't see those there. Thanks for letting me know about these issues, Piplup shiny family has been added and scraggy has been marked as released. [As Far as I can tell Sawk should be male only.](https://bulbapedia.bulbagarden.net/wiki/Sawk_(Pok%C3%A9mon))
