### ISSUE TITLE
Just some missing mons 

### ISSUE THREAD

**Issue by biggif89** [vidoardes/dex#45]
(Missing)
Tornadus therian forme
Meltan 
Melmetal
Galarian Weezing
Burmy sandy and Burmy Trash + evolutions
shellos (east sea) + evolution 

(Not supposed to be gender)
Virizion

(Missing option for Shaddow)
Stantler without bells

**Comment by vidoardes** [comment]
The forms are optional, you can choose to include or remove them in Settings > Edit Dex. This covers Meltan, Galarian, Burmy and Shellos

AFAIK Therian forme is not yet released.

Virizion is now ungendered, and Stantler Bells is available for shadow

**Comment by biggif89** [comment]
thanks for the info. it was the stantler without the bells that needed option for shadow and I still don't see Tornadus therian forme I have it in the pokedex so Im pretty sure its released :)

**Comment by vidoardes** [comment]
Pretty sure only Incarnate is released, normal Stantler has now been made shadow available

**Comment by biggif89** [comment]
yes sorry about that, I was just confused, I think you set the pictures on wrong mon the picture for incarnate is supposed to go on therian and vise versa

**Comment by vidoardes** [comment]
You are correct, the images were the wrogn way around, those are now swapped over. Apologise for the confusion.
