### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by JudithAF** [vidoardes/dex#6]
Hi! Thanks for your time and effort for this project! 
I noticed some small issues:
- Feebas/Milotic shinies are missing
- Spinda 5, and Spinda with Heart are missing (not sure the heart one where it goes in the Dex).
- Palkia is genderless
- Happiny and Froslass can only be Females

BR!

**Comment by vidoardes** [comment]
Thanks for that, those should all now be fixed
